#!/bin/bash

args=("$@")

domain=${args[0]}
region='us-east-1'
stackname=${args[1]}

aws cloudformation delete-stack \
  --region "$region" \
  --stack-name "$stackname"

hosted_zone_id=$(
  aws route53 list-hosted-zones \
    --output text \
    --query 'HostedZones[?Name==`'$domain'.`].Id'
)
echo hosted_zone_id=$hosted_zone_id
aws route53 delete-hosted-zone \
  --id "$hosted_zone_id"


# WARNING! DESTROYS CONTENT AND LOGS!

aws s3 rm --recursive s3://logs.$domain
aws s3 rb s3://logs.$domain
aws s3 rm --recursive s3://$domain
aws s3 rb s3://$domain
aws s3 rb s3://www.$domain
aws s3 rm --recursive s3://codepipeline.$domain
aws s3 rb s3://codepipeline.$domain

# WARNING! DESTROYS CONTENT!

aws codecommit delete-repository \
  --region "$region" \
  --repository-name "$domain"